name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build using node.js
        uses: actions/setup-node@v1
        with:
          node-version: '>=14'
      - run: npm install
      - run: npm run build
